### ISSUE TITLE
Traceback when Reference URI is located inside Signature

### ISSUE THREAD

**Issue by ancc** [XML-Security/signxml#116]
How to use XMLVerifier if Signature block contains Reference tag which URI value references to tag which is inside Signature block, not inside message block.
function _resolve_reference() cannot find it because doc_root doesn't contain Signature tag anymore.
uri_resolver doesn't help because the URI starts with #.

I have verified the xml signature using xmlsec1 from command-line successfully.

Current code:
```
from lxml import etree
from signxml import XMLVerifier


cert = open("cert.pem").read()
data = open('test.xml','r').read()
signed_root = etree.fromstring(data)

verified_data = XMLVerifier().verify(signed_root, x509_cert=cert).signed_xml


Traceback (most recent call last):
  File "verify.py", line 11, in <module>
    verified_data = XMLVerifier().verify(signed_root, x509_cert=cert, require_x509=True).signed_xml
  File "/usr/local/lib/python2.7/site-packages/signxml/__init__.py", line 761, in verify
    payload = self._resolve_reference(root, reference, uri_resolver=uri_resolver)
  File "/usr/local/lib/python2.7/site-packages/signxml/__init__.py", line 239, in _resolve_reference
    raise InvalidInput("Unable to resolve reference URI: {}".format(uri))
signxml.exceptions.InvalidInput: Unable to resolve reference URI: #SP_237F044A71064BFAA9257729967F2F29
```

Example of xml, removed all sensitive parts (signature value is not correct anymore).
```
<?xml version="1.0" encoding="UTF-8"?>
<Msg>
<test>test</test>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#" Id="DS_237F044A71064BFAA9257729967F2F29">
   <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
         <Transforms>
            <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
         </Transforms>
         <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
         <DigestValue>tzCN7xbo72v/bSzC5NDswS9UCw0=</DigestValue>
      </Reference>
      <Reference URI="#SP_237F044A71064BFAA9257729967F2F29" Type="http://uri.etsi.org/01903/v1.1.1#SignedProperties">
         <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
         <DigestValue>YxaaB5xSfTR7hdWZhv1eHInjKH0=</DigestValue>
      </Reference>
   </SignedInfo>
   <SignatureValue>QKL0xlm3FcNqKmt8oL/6xERyjBfC6kBr843OIqUiDKE9xpP7HxTZD7fIM7/tLHfRzsLydnK/KwMYmGCXuHbmE2orbQIb99otIXYY97V9x/GryyP4dm6OLjz9ooLNTtapODHApSCz/YSwBMEhlFSH/tzkdRUgfWKjyMUrk2x+9/4=</SignatureValue>
   <ds:Object xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns="http://uri.etsi.org/01903/v1.1.1#">
      <QualifyingPropertiesReference URI="https://external-url.com">
      <QualifyingPropertiesReference URI="https://external-url.com" />
      <QualifyingProperties Target="#DS_237F044A71064BFAA9257729967F2F29">
         <SignedProperties Id="SP_237F044A71064BFAA9257729967F2F29">
            <SignedSignatureProperties>
               <SigningTime>2018-05-09T11:09:49+03:00</SigningTime>
               <SigningCertificate>
                  <Cert>
                     <CertDigest>
                        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                        <DigestValue>N0IOtuGTDiEjRF12AyiwqH0N90w=</DigestValue>
                     </CertDigest>
                     <IssuerSerial>
                        <ds:X509IssuerName>ISSUER XYZ</ds:X509IssuerName>
                        <ds:X509SerialNumber>1111111111</ds:X509SerialNumber>
                     </IssuerSerial>
                  </Cert>
               </SigningCertificate>
               <SignaturePolicyIdentifier>
                  <SignaturePolicyImplied />
               </SignaturePolicyIdentifier>
            </SignedSignatureProperties>
         </SignedProperties>
         <UnsignedProperties>
            <UnsignedSignatureProperties>
               <SignatureTimeStamp>
                  <HashDataInfo uri="#DS_237F044A71064BFAA9257729967F2F29">
                     <Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
                           <ds:XPath xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">ancestor-or-self::dsig:SignatureValue</ds:XPath>
                        </ds:Transform>
                     </Transforms>
                  </HashDataInfo>
                  <EncapsulatedTimeStamp Id="TST_D7DE97B144FDDEBF099D7353CD2C8B3415655DA2">removed to make it shorter...</EncapsulatedTimeStamp>
               </SignatureTimeStamp>
            </UnsignedSignatureProperties>
         </UnsignedProperties>
      </QualifyingProperties>
   </ds:Object>
</Signature>
</Msg>
```

**Comment by ancc** [comment]
Closing issue. Solved issue by using python-xmlsec.
