### ISSUE TITLE
XMLSigner().sign() TypeError in Python 3.6 & 3.7

### ISSUE THREAD

**Issue by gsong** [XML-Security/signxml#124]
`XMLSigner().sign()` produces the following error when used in Python 3.6 and
3.7:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/signxml/__init__.py", line 362, in sign
    key = load_pem_private_key(key, password=passphrase, backend=default_backend())
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1045, in load_pem_private_key
    password,
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1238, in _load_key
    mem_bio = self._bytes_to_bio(data)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 462, in _bytes_to_bio
    data_ptr = self._ffi.from_buffer(data)
TypeError: from_buffer() cannot return the address of a unicode object
```

Here is the minimal reproducible *working* example using Python 2.7.15 Docker
container:

<details>
<summary>Log of Working Example</summary>

```sh
$ docker run --rm -it -h signxml -w /app -v "${PWD}":/app python:2.7 /bin/bash

# From here we're inside the Docker container

root@xmlsign:/app# pip install signxml

root@xmlsign:/app# pip list
Package      Version
------------ --------
asn1crypto   0.24.0
certifi      2019.3.9
cffi         1.12.2
cryptography 2.6.1
defusedxml   0.5.0
eight        0.4.2
enum34       1.1.6
future       0.16.0
ipaddress    1.0.22
lxml         4.3.2
pip          19.0.1
pycparser    2.19
pyOpenSSL    18.0.0
setuptools   40.6.3
signxml      2.6.0
six          1.12.0
virtualenv   16.3.0
wheel        0.32.3

root@xmlsign:/app# python
Python 2.7.15 (default, Jan 23 2019, 03:48:04)
[GCC 6.3.0 20170516] on linux2

>>> from xml.etree import ElementTree as ET
>>> from signxml import XMLSigner
>>> root = ET.parse('sample.xml').getroot()
>>> key = open('localhost.key').read()
>>> cert = open('localhost.crt').read()
>>> signed = XMLSigner().sign(root, key=key, cert=cert)
>>> signed
<Element {http://www.info.gov.hk/IPD/XMLSchema}e-form at 0x7f04b16afa28>
```

</details>

However, running the exact same code using either Python 3.6 or 3.7 containers,
we get the following error:

<details>
<summary>Log of Non-Working Example</summary>

```
$ docker run --rm -it -h signxml -w /app -v "${PWD}":/app python:3.6 /bin/bash

# From here we're inside the Docker container

root@xmlsign:/app# pip install signxml

root@signxml:/app# pip list
Package      Version
------------ --------
asn1crypto   0.24.0
certifi      2019.3.9
cffi         1.12.2
cryptography 2.6.1
defusedxml   0.5.0
eight        0.4.2
future       0.16.0
lxml         4.3.2
pip          19.0.3
pycparser    2.19
pyOpenSSL    18.0.0
setuptools   40.8.0
signxml      2.6.0
six          1.12.0
wheel        0.33.1

root@signxml:/app# python
Python 3.6.8 (default, Mar  5 2019, 06:26:06)
[GCC 6.3.0 20170516] on linux

>>> from xml.etree import ElementTree as ET
>>> from signxml import XMLSigner
>>> root = ET.parse('sample.xml').getroot()
>>> key = open('localhost.key').read()
>>> cert = open('localhost.crt').read()
>>> signed = XMLSigner().sign(root, key=key, cert=cert)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/signxml/__init__.py", line 362, in sign
    key = load_pem_private_key(key, password=passphrase, backend=default_backend())
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1045, in load_pem_private_key
    password,
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1238, in _load_key
    mem_bio = self._bytes_to_bio(data)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 462, in _bytes_to_bio
    data_ptr = self._ffi.from_buffer(data)
TypeError: from_buffer() cannot return the address of a unicode object
```

</details>

The error seems to stem from `cryptography` but I couldn't find any
corresponding issues there and am not sure how to isolate the issue to the
library or something lower level.

**Comment by gsong** [comment]
OK, I figured it out. In Python 3.6 & 3.7, the key and cert must be bytes instead of strings, so

```py
key = open('localhost.key', 'rb').read()
cert = open('localhost.crt', 'rb').read()
```
