### ISSUE TITLE
how fix this error : i want to create new bench with frappe version 12 but i see that error

### ISSUE THREAD

**Issue by ailanbelal** [XML-Security/signxml#186]
```
error /home/belal/frappe-bench-12/apps/frappe/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/belal/frappe-bench-12/apps/frappe/node_modules/node-sass
Output:
Building: /usr/bin/node /home/belal/frappe-bench-12/apps/frappe/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/belal/frappe-bench-12/apps/frappe/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.19.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/belal/frappe-bench-12/apps/frappe/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/belal/frappe-bench-12/apps/frappe/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/belal/frappe-bench-12/apps/frappe/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/belal/frappe-bench-12/apps/frappe/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.14.0-1036-oem
gyp ERR! command "/usr/bin/node" "/home/belal/frappe-bench-12/apps/frappe/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/belal/frappe-bench-12/apps/frappe/node_modules/node-sass
gyp ERR! node -v v14.19.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bench/commands/make.py", line 70, in init
    init(
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/system.py", line 78, in init
    get_app(
  File "/usr/local/lib/python3.8/dist-packages/bench/app.py", line 371, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bench/app.py", line 198, in install
    install_app(
  File "/usr/local/lib/python3.8/dist-packages/bench/app.py", line 428, in install_app
    bench.run("yarn install", cwd=app_path)
  File "/usr/local/lib/python3.8/dist-packages/bench/bench.py", line 43, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/usr/local/lib/python3.8/dist-packages/bench/utils/__init__.py", line 126, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError

```

**Comment by kislyuk** [comment]
This does not appear to be related to SignXML.
