### ISSUE TITLE
ca_path isn't finding proper certificate

### ISSUE THREAD

**Issue by nbastin** [XML-Security/signxml#49]
If I set `ca_path` in `verify`, it fails:

```
>>> ds.verify(id_attribute='xml:id', ca_path="/home/nbastin/geni-roots", validate_schema=False)                                                                                     
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 657, in verify
    verify_x509_cert_chain(cert_chain, ca_pem_file=ca_pem_file, ca_path=ca_path)
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 735, in verify_x509_cert_chain
    raise InvalidCertificate(e)
InvalidCertificate: [20, 0, 'unable to get local issuer certificate']
```

But if I pass it the proper PEM in `ca_pem_file`, which is in that path, it "works"  (sortof - not sure what this other problem is):

```
>>> ds.verify(id_attribute='xml:id', ca_pem_file="geni-roots/ch.geni.net-ca.pem", validate_schema=False)                                                                            
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 671, in verify
    raise InvalidSignature("Signature verification failed: {}".format(reason))
InvalidSignature: Signature verification failed: bad signature
```

**Comment by kislyuk** [comment]
I'm not sure what the issue was here, but I suspect that since no positive example was provided, the problem was not as stated in the issue title. If you are still encountering this error, please reopen with a complete reproduction.
