### ISSUE TITLE
Cannot verify signatures

### ISSUE THREAD

**Issue by Gallaecio** [XML-Security/signxml#66]
I am trying to verify the signature of two XML documents.

When I try to verify an example XML document from the SII (Chile’s IRS), I get:

```
Traceback (most recent call last):
  File "test_verify.py", line 30, in <module>
    verifier.verify(xml_tree, x509_cert=cert)
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 666, in verify
    raise InvalidSignature("Signature verification failed: {}".format(reason))
InvalidSignature: Signature verification failed: block type is not 01
```

When I try to verify an XML document generated and signed by myself using `signxml`, I get:

```
Traceback (most recent call last):
  File "test_verify.py", line 30, in <module>
    verifier.verify(xml_tree, x509_cert=cert)
  File "/usr/local/lib/python2.7/dist-packages/signxml/__init__.py", line 666, in verify
    raise InvalidSignature("Signature verification failed: {}".format(reason))
InvalidSignature: Signature verification failed: bad signature
```

This is the script I am using:

```
# coding=utf-8

from tempfile import TemporaryFile
from traceback import print_exc
from urllib2 import urlopen
from zipfile import ZipFile

from lxml.etree import parse

from signxml import XMLVerifier


verifier = XMLVerifier()

temporary_file = TemporaryFile()
remote_file = urlopen('http://www.sii.cl/factura_electronica/ejemplo_xml.zip')
temporary_file.write(remote_file.read())
zip_file = ZipFile(temporary_file)
xml_file = zip_file.open('F60T33-ejemplo.xml')
xml_tree_1 = parse(xml_file)

xml_tree_2 = parse(urlopen('http://pastebin.com/raw/1jCkqCUX'))

for xml_tree in (xml_tree_1, xml_tree_2):
    try:
        cert = xml_tree.find(
            './/{http://www.w3.org/2000/09/xmldsig#}X509Certificate').text
        cert = '-----BEGIN CERTIFICATE-----\n{}' \
               '\n-----END CERTIFICATE-----\n'.format(cert.strip('\n'))
        verifier.verify(xml_tree, x509_cert=cert)
        print(u"Result: SUCCESS")
    except:
        print_exc()
        print(u"Result: FAILURE")
    print('')
```

Any idea of what I am doing wrong, or how to find out?

**Comment by kislyuk** [comment]
Both errors are emitted by openssl when it fails to verify the signature. The first one is due to a signature format that openssl does not recognize (i.e. there is an incompatibility between the signing method that SII used and the verifying method that openssl uses). This *may* have been [addressed](https://github.com/openssl/openssl/pull/612) in OpenSSL 1.1.0, but I'm not sure.

I can't really say much about the second error - are you absolutely sure that you're passing the correct private key and cert pair when signing? I re-signed your document with a letsencrypt-issued cert and key, and verification succeeded.

**Comment by kislyuk** [comment]
Closing due to lack of response.
